# Generated by Django 5.2.8 on 2025-11-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kudo',
            old_name='sender',
            new_name='kudos_from',
        ),
        migrations.RenameField(
            model_name='kudo',
            old_name='receiver',
            new_name='kudos_to',
        ),
    ]
